---
title: "Dido's problem"
author: "Robin Hankin"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## How to enclose the maximum area for a given length of string

\newcommand{\di}[2]{\frac{\partial{#1}}{\partial{#2}}}
\newcommand{\cx}{\cosh{\left(\frac{x-x_0}{a}\right)}}
\newcommand{\sx}{\sinh{\left(\frac{x-x_0}{a}\right)}}
\newcommand{\tx}{\tanh{\left(\frac{x-x_0}{a}\right)}}
\newcommand{\sech}{\operatorname{sech}}
\newcommand{\el}[1]{\frac{d}{dx}\di{#1}{y'} - \di{#1}{y}}




We wish to minimize the functional $F[y] = \lambda y+\sqrt{1+y'^2}$.
Here is the Beltrami identity:

\begin{equation}
F - y'\di{F}{y'} = C
\end{equation}


\begin{equation}
\lambda y+\sqrt{1+y'^2} - \frac{y'^2}{\sqrt{1+y'^2}} = C
\end{equation}


\begin{equation}
\sqrt{1+y'^2} - \frac{y'^2}{\sqrt{1+y'^2}} = C+\lambda y
\end{equation}


\begin{equation}
(C+\lambda y)\sqrt{1 + y'^2} =1
\end{equation}


\begin{equation}
(C+\lambda y)\sqrt{1 + y'^2} =1
\end{equation}

\begin{equation}
y' = \sqrt{\frac{1}{(C+\lambda y)^2}-1}
\end{equation}


\begin{equation}
\int\frac{dy}{\sqrt{\frac{1}{(C+\lambda y)^2}-1}} = \int dx
\end{equation}

\begin{equation}
x - K =  \frac{(C+\lambda y)^2-1}{\lambda(C+\lambda y)\sqrt{\frac{1}{(C+\lambda y)^2}-1}}
\end{equation}

[the reason  for the negative sign for $K$ will become apparent]

\begin{equation}
\sqrt{1-(C+\lambda y)^2} = \lambda(x-K)
\end{equation}

\begin{equation}
(C+\lambda y)^2+ \lambda^2(x-K)^2 =1
\end{equation}

\begin{equation}\label{recognisably_a_circle}
(y + C/\lambda)^2+ (x-K)^2 = 1/\lambda^2
\end{equation}

Equation \ref{recognisably_a_circle} is recognisably an arc of a
circle with radius $r=1/\lambda$.  We will impose boundary
conditions: $y(a)=y(b)=0$.  That is, the curve passes through points
$(a,0)$ and $(b,0)$.  Equation \ref{recognisably_a_circle} gives

\begin{eqnarray}
C^2 + (a-K)^2/r^2 &=& 1\\
C^2 + (b-K)^2/r^2 &=& 1
\end{eqnarray}

Subtracting gives $(a-K)^2=(b-K)^2$, or $(a-K)=\pm(b-K)$; the positive
root gives $a=b$ so is disallowed and we are left with $K=(a+b)/2$,
the midpoint between $a$ and $b$ [which is why the negative sign was
chosen above].  Substituting gives $C^2=1-M^2/r^2$.
Equation \ref{recognisably_a_circle} becomes

\begin{equation}
(y \pm r\sqrt{1-M^2/r^2})^2+ (x-K)^2 = r^2
\end{equation}

The different signs give arcs that are convex up or convex down.
Taking the negative sign for convenience, we might know that the
maximum height of the circle is, say, $H$, and then we know that the
arc passes through $(K,H)$ which gives us a quadratic for $r^2$.  But
it is easier to use geometry [in particular, the intersecting chords
theorem] to give $(a-b)^2=4H(2r-H)$, which can be used to solve for
$r$.

## Alternative approach

We seek a function $z=z(t)=(x(t),y(t))$ that maximizes the enclosed
area subject to a total arc length constraint.  The Lagrangian would
be

\begin{equation}\Lambda = \frac{1}{2}\left(x\dot{y} -\dot{x}y\right) +
\lambda\sqrt{\dot{x}^2+\dot{y}^2}
\end{equation}

The area is given by the first term and $\lambda$ is the Lagrange
undetermined multiplier.


\begin{equation}
\frac{d}{dt}\di{\Lambda}{z} = \di{\Lambda}{z}
\end{equation}

We have two Euler-Lagrange equations for $x$ and $y$:

\begin{eqnarray}
\frac{d}{dt}\di{\Lambda}{\dot{x}} - \di{\Lambda}{x} &=& 0\\
\frac{d}{dt}\di{\Lambda}{\dot{y}} - \di{\Lambda}{y} &=& 0
\end{eqnarray}


Applying the partial differentiation operators:

\begin{eqnarray}
\frac{d}{dt}\left[\frac{-y}{2} +
\frac{\lambda\dot{x}}{\sqrt{\dot{x}^2+\dot{y}^2}}\right]
-\frac{\dot{y}}{2} &=& 0\\
\frac{d}{dt}\left[\frac{+x}{2} + \frac{\lambda\dot{y}}{\sqrt{\dot{x}^2+\dot{y}^2}}\right]
+\frac{\dot{x}}{2} &=& 0
\end{eqnarray}

\begin{eqnarray}
\frac{d}{dt}\left[\frac{\lambda\dot{x}}{\sqrt{\dot{x}^2+\dot{y}^2}}\right]
&=& \dot{y}\\
\frac{d}{dt}\left[\frac{\lambda\dot{y}}{\sqrt{\dot{x}^2+\dot{y}^2}}\right]
&=& -\dot{x}
\end{eqnarray}

Integrating both sides of each equation with respect to $t$
\begin{eqnarray}
\frac{\lambda\dot{x}}{\sqrt{\dot{x}^2+\dot{y}^2}}
&=& y-b\\
\frac{\lambda\dot{y}}{\sqrt{\dot{x}^2+\dot{y}^2}}
&=& a-x
\end{eqnarray}


Squaring and summing:

\begin{equation}
(x-a)^2 + (y-b)^2 = \lambda^2
\end{equation}



# Perturbation analysis



We will make land with a large $y$ coordinate worth slightly more.  We
will maximize $\int (y+\epsilon y^2)\,dx$, subject to the length
constraint.  Using standard perturbation techniques we have

\begin{equation}
F= y + \Lambda\sqrt{1+y'^2}\qquad G=y^2 + \lambda\sqrt{1+y'^2}
\end{equation}

We can show that $\Lambda=1$ [it is the radius of the circle and we
will look only at unit radius circles from now on] so we will ignore it.

\begin{equation}\label{factorized_eqn}
\left(z\di{}{y} + z'\di{}{y'} + z''\di{}{y''}\right)
\left(\el{F}\right) + \left(\el{G}\right) = 0
\end{equation}

We have 

\begin{eqnarray}
  \el{F} &=& \frac{d}{dt}\left[\frac{y'}{\sqrt{1+y'^2}}\right]-1  = \frac{y''}{(1+y'^2)^{3/2}}-1\\
  \el{G} &=& \frac{\lambda y''}{(1+y'^2)^{3/2}} -2y
\end{eqnarray}

So equation \ref{factorized_eqn} gives us

\begin{eqnarray}
   z' \di{}{y' }\left[\frac{y''}{(1+y'^2)^{3/2}}-1\right]
 + z''\di{}{y''}\left[\frac{y''}{(1+y'^2)^{3/2}}-1\right] 
 +    \frac{\lambda y''}{(1+y'^2)^{3/2}} - 2y &=& 0\nonumber\\
-3z' \left[\frac{y'y''}{(1+y'^2)^{5/2}}\right]
+ z''\left[\frac{1}{(1+y'^2)^{3/2}}\right]
+    \frac{\lambda y''}{(1+y'^2)^{3/2}} - 2y &=& 0\\
\end{eqnarray}


Simplifying

\begin{equation}
z'' - 3z'\frac{y'y''}{1+y'^2} + \lambda y'' - 2y(1+y'^2)^{3/2}=0
\end{equation}

Now a standard circle, $x^2+y^2=1$, is problematic because the
gradient is infinite at the boundaries $x=\pm 1$.  We will take a
unit-radius circle with center $(0,-\sqrt{2}/2)$, giving $x^2 +
(y+\sqrt{2}/2)^2=1$, or $y=\sqrt{1-x^2}-\sqrt{2}/2$.  We find that
$y'=\frac{-x}{\sqrt{1-x^2}}$ and $1+y'^2=\frac{1}{1-x^2}$.  Also $y'' =
\frac{-1}{(1-x^2)^{3/2}}$.

\begin{eqnarray}
   z'' 
-3z'\frac{\frac{x}{\sqrt{1-x^2}}\cdot\frac{1}{(1-x^2)^{3/2}}}{\frac{1}{1-x^2}}
+ \frac{\lambda\frac{-1}{(1-x^2)^{3/2}}}{(1-x^2)^{-3/2}}
- \frac{2}{1-x^2}-\frac{\sqrt{2}}{(1-x^2)^{3/2}}
&=& 0
\end{eqnarray}

Restating:

\begin{equation}
z'' -3z'\frac{x}{1-x^2} = \lambda +  \frac{2}{1-x^2} + \frac{\sqrt{2}}{(1-x^2)^{3/2}}
\end{equation}


Writing $z_\lambda(x)$ for a solution of this equation, we want to
ensure that the total string length is preserved.  To wit:

\begin{eqnarray}
\int_{-\frac{\sqrt{2}}{2}}^{\frac{\sqrt{2}}{2}}
\sqrt{1+\left({1+(y' + \epsilon z')^2}\right)}\,dx
&=&
\int_{-\frac{\sqrt{2}}{2}}^{\frac{\sqrt{2}}{2}}
\sqrt{1+\left({1+y'^2}\right)}\,dx
\end{eqnarray}


Differentiating (with respect to $\epsilon$):


\begin{eqnarray}
\di{}{\epsilon}\int_{-\frac{\sqrt{2}}{2}}^{\frac{\sqrt{2}}{2}}
\left.\sqrt{1+\left({1+(y' + \epsilon z')^2}\right)}\,dx\right|_{\epsilon=0}
&=&
\int_{-\frac{\sqrt{2}}{2}}^{\frac{\sqrt{2}}{2}}
\di{}{\epsilon}
\left. \sqrt{1 + (y' + \epsilon z')^2}\right|_{\epsilon=0}\,dx\nonumber\\
&=&
\int_{-\frac{\sqrt{2}}{2}}^{\frac{\sqrt{2}}{2}}
\frac{y'z\,dx}{\sqrt{1+y'^2}}\nonumber\\
&=&
\int_{-\frac{\sqrt{2}}{2}}^{\frac{\sqrt{2}}{2}}
-x\,z(x)\,dx\nonumber\\
&=& 0
\end{eqnarray}
