---
-title: "Perturbing the Euler-Lagrange equations for calculus of variations: a first-order analysis"
author: "Robin Hankin"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***This file is now considered to contain a subtle yet important
logical fallacy which I cannot quite express clearly.  But it is
definitely incorrect and misleading.  A corrected version is under
version control at `euler_lagrange_perturbed.Rmd`. ***

\newcommand{\di}[2]{\frac{\partial{#1}}{\partial{#2}}}
\newcommand{\cx}{\cosh{\left(\frac{x-x_0}{a}\right)}}
\newcommand{\sx}{\sinh{\left(\frac{x-x_0}{a}\right)}}
\newcommand{\tx}{\tanh{\left(\frac{x-x_0}{a}\right)}}
\newcommand{\sech}{\operatorname{sech}}

Consider a functional $F=F(x,y,y';\lambda)$ and a perturbation:

\begin{eqnarray}
y  &\longrightarrow&  y(x) + \epsilon z(x)\\
y' &\longrightarrow&  y'(x) + \epsilon z'(x)\\
F  &\longrightarrow&  F + \epsilon G(x,y,y')
\end{eqnarray}


\begin{eqnarray}
\frac{d}{dx}\di{F}{y'}=\di{F}{y}\nonumber\longrightarrow\\
\frac{d}{dx}\left[\di{}{y'}\left(F(x,y+\epsilon z,y'+\epsilon z')+\epsilon G(x,y+\epsilon z,y'+\epsilon z')\right)\right] =\\
\di{}{y}\left[F(x,y+\epsilon z,y'+\epsilon z')
+\epsilon G(x,y+\epsilon z,y'+\epsilon z')\right]
\end{eqnarray}

Above we write $y$ for $y(x)$ etc.  We have to remember that
$y,y',z,z'$ are functions of $x$.  Now neglect terms of order
$\epsilon^2$ and above, and continue to neglect them:

\begin{equation}
\frac{d}{dx}\left[\di{}{y'}\left(F(x,y+\epsilon z,y'+\epsilon z')+\epsilon G(x,y,y')\right)\right] =
\di{}{y}\left[F(x,y+\epsilon z,y'+\epsilon z')+\epsilon G(x,y,y')\right]
\end{equation}

\begin{equation}
\frac{d}{dx}\left[\di{}{y'}\left(
F(x,y,y') + \epsilon z\di{F}{y} + \epsilon z'\di{F}{y'} 
+\epsilon G(x,y,y')\right)\right] =
\di{}{y}\left[
F(x,y+\epsilon z,y'+\epsilon z') + \epsilon G(x,y,y')\right]
\end{equation}

\begin{equation}
\frac{d}{dx}\left[\di{}{y'}\left(
F(x,y,y') + \epsilon z\di{F}{y} + \epsilon z'\di{F}{y'} 
+\epsilon G(x,y,y')\right)\right] =
\di{}{y}\left[
F(x,y,y') + \epsilon z\di{F}{y} + \epsilon z'\di{F}{y'} + \epsilon G(x,y,y')\right]
\end{equation}

The $\epsilon^0$ term is just the Euler-Lagrange equation, which is
known to be true.  The first order term is:

\begin{equation}\label{EL1}
\frac{d}{dx}\left[\di{}{y'}\left(
z\di{F}{y} + z'\di{F}{y'} + G\right)\right] =
\di{}{y}\left(z\di{F}{y} + z'\di{F}{y'} + G\right)
\end{equation}

(above we have to remember that $G=G(x,y,y')$).


