---
title: "Perturbing the catenary: a first-order analysis"
author: "Robin Hankin"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The catenary.

\newcommand{\di}[2]{\frac{\partial{#1}}{\partial{#2}}}
\newcommand{\cx}{\cosh{\left(\frac{x-x_0}{a}\right)}}
\newcommand{\sx}{\sinh{\left(\frac{x-x_0}{a}\right)}}
\newcommand{\tx}{\tanh{\left(\frac{x-x_0}{a}\right)}}
\newcommand{\sech}{\operatorname{sech}}

We start with the Euler-Lagrange equation

\begin{equation}
\frac{d}{dx}\di{F}{y'} -\di{F}{y}=0
\end{equation}

and if $\di{F}{x}=0$ we have the Beltrami equation

\begin{equation}
F-y'\di{F}{y'}=C
\end{equation}

For a catenary we have

\begin{equation}
F=\sqrt{1+(y')^2}(y + \lambda)
\end{equation}

so Beltrami applies giving

\begin{equation}
\sqrt{1+y'^2}(y + \lambda)-\frac{y'^2(y+\lambda)}{\sqrt{1+y'^2}}=C
\end{equation}

Simplifying

\begin{equation}
(y+\lambda)=C\sqrt{1+y'^2}
\end{equation}

or

\begin{equation}
dx=\frac{dy}{\sqrt{\left(\frac{y+\lambda}{C}\right)^2-1}}
\end{equation}

Substituting $u=(y+\lambda)/C$ so $du=dy/C$ we have

\begin{equation}
x=\int\frac{C\,du}{\sqrt{u^2-1}} =
C\operatorname{acosh}\left(\frac{y+\lambda}{C}\right)+K
\end{equation}

giving, in more conventional notation,

\begin{equation}
y = y_0 + a\operatorname{cosh}\left(\frac{x-x_0}{a}\right)
\end{equation}

Here for simplicity we use $x_0=y_0=0$, $a=1$.


# Perturbing the catenary.

The first-order corrective term for EL is:

\begin{equation}\label{EL1}
\frac{d}{dx}\left[\di{}{y'}\left(
z\di{F}{y} + z'\di{F}{y'} + G\right)\right] =
\di{}{y}\left(z\di{F}{y} + z'\di{F}{y'} + G\right)
\end{equation}


Now we consider a flexible chain minimising its potential energy in a
slightly perturbed potential field $y + \epsilon\phi(x,y)$ where
$\epsilon$ is sufficiently small to neglect $\epsilon^2$ and higher.
Here we have $F=\sqrt{1+y'^2}(y+\lambda)$ and
$G=\sqrt{1+y'^2}\phi(x,y)$.

Before we apply it to the catenary we need to consider the form of
$G$, which will include a constraint.  We have
$F=\sqrt{1+y'^2}(y+\lambda)$ giving
$y(x)=a\cosh\left(\frac{x-x_0}{a}\right)$.  At first glance, the
perturbation $\epsilon G$ is just $\epsilon\phi(x,y)\sqrt{1+y'^2}$.
But there is a constraint here.  The overall length should not be
altered.  As above, we have

\begin{eqnarray}
\int_{x=-a}^{x=+a}\sqrt{1+y'^2}dx &\longrightarrow& \int_{x=-a}^{x=+a}\sqrt{1+(y+\epsilon z)'^2}dx\\
&=& \int_{x=-a}^{x=+a}\sqrt{1+y'^2 +2\epsilon y'z'}dx \\
&=& \int_{x=-a}^{x=+a}\left(\sqrt{1+y'^2} + \epsilon\frac{y'z'}{\sqrt{1+y'^2}}\right)dx
\end{eqnarray}


So the constraint should be that 

\begin{equation}
\int_{x=-a}^{x=+a}\frac{y'z'\,dx}{\sqrt{1+y'^2}}=0
\end{equation}

Reducing to 

\begin{equation}
\int_{x=-a}^{x=+a}z'(x)\tanh(x)\,dx=0
\end{equation}

Using the product rule we get

\begin{equation}
\int_{x=-a}^{x=+a}z(x)\sech^2 x\,dx=0
\end{equation}


So the appropriate constraint on G would be 

\begin{equation}
G = \phi(x,y)\sqrt{1+y'^2} + \mu z'(x)\frac{y'}{\sqrt{1+y'^2}}
\end{equation}

where $\mu$ is an undetermined multiplier.  BUT THIS IS WRONG.  G is
not being optimized (actually $F+\epsilon G$ is being optimized).  For
convenience here is equation \ref{EL1}:

\begin{equation}
\frac{d}{dx}\left[\di{}{y'}\left(
z\di{F}{y} + z'\di{F}{y'} + G\right)\right] =
\di{}{y}\left(z\di{F}{y} + z'\di{F}{y'} + G\right)\nonumber
\end{equation}


\begin{equation}
F = (y+\lambda)\sqrt{1+y'^2}+ \frac{\mu y'z'}{\sqrt{1+y'^2}},\qquad 
G = \phi(x,y)\sqrt{1+y'^2}
\end{equation}


\begin{equation}
\frac{d}{dx}\di{H}{y'}=\di{H}{y},\qquad
H=z\di{F}{y} + z'\di{F}{y'} + G
\end{equation}

We find that 

\begin{eqnarray}
H &=& z\di{F}{y} + z'\di{F}{y'} + G \nonumber\\
  &=& z\underbrace{\sqrt{1+y'^2}}_{\partial F/\partial y} + 
      z'
	  \underbrace{\left(
	     \frac{y'(y+\lambda)}{\sqrt{1+y'^2}} + \frac{\mu}{(1+y'^2)^{3/2}}
	     \right)
	  }_{
	     \partial F/\partial y'
	  } + 
      \underbrace{\phi(x,y)\sqrt{1+y'^2}}_{G}\nonumber\\
  &=& (z+\phi(x,y))\sqrt{1+y'^2}  + \frac{y'(y+\lambda)z'}{\sqrt{1+y'^2}} + \frac{\mu z'}{(1+y'^2)^{3/2}}
\end{eqnarray}

We have

\begin{equation}
\di{H}{y'} = 
  \frac{(z+\phi)y'}{\sqrt{1+y'^2}}
+ \frac{(y+\lambda)z'}{(1+y'^2)^{3/2}}
- \frac{3\mu y'z'}{(1+y'^2)^{5/2}}
\end{equation}

\begin{equation}
\di{H}{y} = 
    \phi_y\sqrt{1+y'^2}
 +  \frac{y'z'}{\sqrt{1+y'^2}}
 \end{equation}

\begin{eqnarray}
\frac{d}{dx}\di{H}{y'} &=& \di{H}{y}\nonumber\\
\frac{d}{dx}
\left[
  \frac{(z+\phi)y'}{\sqrt{1+y'^2}}
+ \frac{(y+\lambda)z'}{(1+y'^2)^{3/2}}
- \frac{3\mu y'z'}{(1+y'^2)^{5/2}}
\right]
&=& 
    \phi_y\sqrt{1+y'^2}
 +  \frac{y'z'}{\sqrt{1+y'^2}}
\end{eqnarray}

Now we remind ourselves that $y=y_0+\cx$ and $y'=\sx$, so
$\sqrt{1+y'^2}=\cx$ and set $x_0=y_0=0$, $a=1$, so $y=\cosh x$ and
$y'=\sinh x$:
